
package com.j4ltechnologies.formation.ws.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WsCompte", targetNamespace = "http://impls.ws.soap.ws.formation.j4ltechnologies.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsCompte {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://impls.ws.soap.ws.formation.j4ltechnologies.com/WsCompte/crediterRequest", output = "http://impls.ws.soap.ws.formation.j4ltechnologies.com/WsCompte/crediterResponse")
    public void crediter(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://impls.ws.soap.ws.formation.j4ltechnologies.com/WsCompte/createCompteRequest", output = "http://impls.ws.soap.ws.formation.j4ltechnologies.com/WsCompte/createCompteResponse")
    public void createCompte(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.j4ltechnologies.formation.ws.soap.Compte
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://impls.ws.soap.ws.formation.j4ltechnologies.com/WsCompte/findCompteRequest", output = "http://impls.ws.soap.ws.formation.j4ltechnologies.com/WsCompte/findCompteResponse")
    public Compte findCompte(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://impls.ws.soap.ws.formation.j4ltechnologies.com/WsCompte/debiterRequest", output = "http://impls.ws.soap.ws.formation.j4ltechnologies.com/WsCompte/debiterResponse")
    public void debiter(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1);

}
